version: "3.8"
services:
  best-number-frontend:
    image: best-number-frontend
    build: ./1-best-number-frontend
    stdin_open: true
    tty: true
    depends_on:
      - best-number-backend

  best-number-backend:
    image: best-number-backend
    build: ./2-best-number-backend
    depends_on:
      - best-number-db

  best-number-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: best-number
    volumes:
      - best-number-db-data:/var/lib/postgresql/data
      - ./3-best-number-db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  best-number-db-data:
